backend:
  name: github
  repo: Matsico/Matsico.github.io
  branch: main
  base_url: https://api.github.com
  auth_endpoint: https://github.com/login/oauth/authorize

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "producten"
    label: "Assortiment"
    folder: "content/producten"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naam", name: "title", widget: "string" }
      - { label: "Categorie", name: "categorie", widget: "select", options: ["Vis", "Aquarium", "Accessoires"] }
      - { label: "Prijs", name: "prijs", widget: "string" }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - { label: "Afbeelding", name: "image", widget: "image" }
