backend:
  name: github
  repo: Matsico/Matsico.github.io
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "producten"
    label: "Assortiment"
    folder: "content/producten"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naam", name: "title", widget: "string" }
      - { label: "Beschrijving", name: "description", widget: "text" }
      - { label: "Afbeelding", name: "image", widget: "image" }
